// RestaurantInfo
export const UPDATE_PARTNER_PROFILE_PICTURE = 'UPDATE_PARTNER_PROFILE_PICTURE'
export const UPDATE_AADHAR_PICTURE = 'UPDATE_AADHAR_PICTURE'
export const UPDATE_DRIVING_LICENCE_PICTURE = 'UPDATE_DRIVING_LICENCE_PICTURE'
export const UPDATE_PARTNER_NAME = 'UPDATE_PARTNER_NAME'
export const UPDATE_PARTNER_LAT = 'UPDATE_PARTNER_LAT'
export const UPDATE_PARTNER_LNG = 'UPDATE_PARTNER_LNG'
export const UPDATE_PARTNER_ONLINE_STATUS = 'UPDATE_PARTNER_ONLINE_STATUS'
export const RESET = 'RESET'